theme = "base16_default_dark"
[editor]
mouse = true
idle-timeout = 0
line-number = "absolute"
cursorline = true
color-modes = true
bufferline = "multiple"
preview-completion-insert = false
lsp.display-inlay-hints = true
true-color = true
auto-format = false

completion-replace = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner","file-name","total-line-numbers","position-percentage"]
center = ["version-control"]
right = ["file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true

[keys.insert]
C-i = "normal_mode" 

[keys.normal.z]
j = "scroll_up"
k = "scroll_down"

[keys.normal]
C-f = ":format"
C-s = ":w" # Maps Ctrl-s to the typable command :w which is an alias for :write (save file)

[keys.normal."+"]
m = ":run-shell-command make"
c = ":run-shell-command cargo build"
t = ":run-shell-command cargo check"
r = ":run-shell-command cargo run"
